# Generated by Django 3.2 on 2021-06-01 04:15

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='autograder_path',
            field=models.FilePathField(blank=True, match='.*\\.zip', null=True, path=pathlib.PurePosixPath('/home/clarence/code/athena/autograder'), recursive=True, verbose_name='autograder zip path'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='autograde_mode',
            field=models.IntegerField(choices=[(0, 'No Autograder'), (1, 'Autograde -- results released immediately')], default=0, verbose_name='autograder options'),
        ),
    ]
