# Generated by Django 3.2 on 2021-06-01 04:25

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_auto_20210601_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='autograder_path',
            field=models.FilePathField(blank=True, default='', match='.*\\.zip', path=pathlib.PurePosixPath('/home/clarence/code/athena/autograder'), recursive=True, verbose_name='autograder zip path'),
        ),
    ]
