# Generated by Django 3.2 on 2021-06-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_alter_assignment_autograder_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='autograderresult',
            name='autograde_success',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='autograder_path',
            field=models.FilePathField(blank=True, default='', match='.*\\.zip', path='/home/clarence/code/athena/autograder', recursive=True, verbose_name='autograder zip path'),
        ),
        migrations.AlterField(
            model_name='autograderresult',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(3, 'Past'), (0, 'Submitted (waiting for grade)'), (2, 'Graded (manually)'), (1, 'Graded (autograde)'), (4, 'Waiting for autograde')], default=0),
        ),
    ]
